config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"

  namespace :mypos do
    get "dashboard", to: "dashboard#index"
    root to: "dashboard#index"

    resources :customers, :suppliers, :categories, :units, :products, :sales, :product_sellings
  end

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :unit
  belongs_to :user
end

app/controllers/mypos/application_controller.rb
class Mypos::ApplicationController < ActionController::Base
  helper: application
  protect_from_forgery with: :exception
  # check_authorization

  # rescue_from CanCan::AccessDenied do
  #   redirect_to root_path, alert: "Access Denied"
  # end
  before_action :authenticate_user!
end

app/controllers/mypos/categories_controller.rb
class Mypos::CategoriesController < ApplicationController
  before_action :find_category, except: [:index, :new, :create]

  def index
    @categories = Category.where(user_id: current_user).paginate(:page => params[:page], :per_page => 15)
  end

  def show
  end

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      flash[:notice] = "Successfully added category"
      redirect_to mypos_categories_path
    else
      flash[:alert] = "Something went wrong"
      render "new"
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Successfully updated category"
      redirect_to mypos_category_path(@category)
    else
      flash[:alert] = "Something went wrong"
      render "edit"
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = "Successfully deleted category"
    redirect_to mypos_categories_path
  end

  private
    def find_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/mypos/customers_controller.rb
class Mypos::CustomersController < ApplicationController
  before_action :find_customer, except: [:index, :new, :create]

  def index
    @customers = Customer.where(user_id: current_user).paginate(:page => params[:page], :per_page => 15)
  end

  def show
  end

  def new
    @customer = current_user.customers.build
  end

  def create
    @customer = current_user.customers.build(customer_params)

    if @customer.save
      flash[:notice] = "Successfully added customer"
      redirect_to mypos_customers_path
    else
      flash[:alert] = "Something went wrong"
      render "new"
    end
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      flash[:notice] = "Successfully updated customer"
      redirect_to mypos_customer_path(@customer)
    else
      flash[:alert] = "Something went wrong"
      render "edit"
    end
  end

  def destroy
    @customer.destroy
    flash[:notice] = "Successfully deleted customer"
    redirect_to mypos_customers_path
  end

  private
    def find_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:company_name, :name, :email, :phone_number, :website, :address, :city, :state, :zip, :country)
    end
end

app/controllers/mypos/dashboard_controller.rb
class Mypos::DashboardController < ApplicationController
  def index
    @customer = Customer.count
  end
end

app/controllers/mypos/product_sellings_controller.rb
class Mypos::ProductSellingsController < ApplicationController
  before_action :find_product_selling

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
    def product_selling_params
    end

    def find_product_selling
    end
end

app/controllers/mypos/products_controller.rb
class Mypos::ProductsController < ApplicationController
  before_action :find_product, except: [:index, :new, :create]

  def index
    @products = Product.where(user_id: current_user).paginate(:page => params[:page], :per_page => 15)
  end

  def show
  end

  def new
    @product = current_user.products.build
  end

  def create
    @product = current_user.products.build(product_params)

    if @product.save
      flash[:notice] = "Successfully added product"
      redirect_to mypos_products_path
    else
      flash[:alert] = "Something went wrong"
      render "new"
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:notice] = "Successfully updated product"
      redirect_to mypos_product_path(@product)
    else
      flash[:alert] = "Something went wrong"
      render "edit"
    end
  end

  def destroy
    @product.destroy
    flash[:notice] = "Successfully deleted product"
    redirect_to mypos_products_path
  end

  private
    def find_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:category_id, :unit_id, :code_product, :name, :size, :description, :buy_cost, :sell_cost, :quantity)
    end
end

app/controllers/mypos/sales_controller.rb
class Mypos::SalesController < ApplicationController
  before_action :find_sale, except: [:index, :new, :create]

  def index
    @sales = Sale.where(user_id: current_user).paginate(:page => params[:page], :per_page => 15)
  end

  def show
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = current_user.sales.build(sale_params)

    if @sale.save
      flash[:notice] = "Successfully added sale"
      redirect_to mypos_sales_path
    else
      flash[:alert] = "Something went wrong"
      render "new"
    end
  end

  def edit
  end

  def update
    if @sale.update(sale_params)
      flash[:notice] = "Successfully updated sale"
      redirect_to mypos_sale_path(@sale)
    else
      flash[:alert] = "Something went wrong"
      render "edit"
    end
  end

  def destroy
    @sale.destroy
    flash[:notice] = "Successfully deleted sale"
    redirect_to mypos_sales_path
  end

  private
    def sale_params
      params.require(:sale).permit(:customer_id, :payment_method_id, :payment_status_id, :product_id, :sell_cost, :quantity)
    end

    def find_sale
      @sale = Sale.find(params[:id])
    end
end

app/controllers/mypos/suppliers_controller.rb
class Mypos::SuppliersController < ApplicationController
  before_action :find_supplier, except: [:index, :new, :create]

  def index
    @suppliers = Supplier.where(user_id: current_user).paginate(:page => params[:page], :per_page => 15)
  end

  def show
  end

  def new
    @supplier = current_user.suppliers.build
  end

  def create
    @supplier = current_user.suppliers.build(supplier_params)

    if @supplier.save
      flash[:notice] = "Successfully added supplier"
      redirect_to mypos_suppliers_path
    else
      flash[:alert] = "Something went wrong"
      render "new"
    end
  end

  def edit
  end

  def update
    if @supplier.update(supplier_params)
      flash[:notice] = "Successfully updated supplier"
      redirect_to mypos_supplier_path(@supplier)
    else
      flash[:alert] = "Something went wrong"
      render "edit"
    end
  end

  def destroy
    @supplier.destroy
    flash[:notice] = "Successfully deleted supplier"
    redirect_to mypos_suppliers_path
  end

  private
    def find_supplier
      @supplier = Supplier.find(params[:id])
    end

    def supplier_params
      params.require(:supplier).permit(:company_name, :name, :email, :phone_number, :website, :address, :city, :state, :zip, :country, :comment)
    end
end

app/controllers/mypos/units_controller.rb
class Mypos::UnitsController < ApplicationController
  before_action :find_unit, except: [:index, :new, :create]

  def index
    @units = Unit.where(user_id: current_user).paginate(:page => params[:page], :per_page => 15)
  end

  def show
  end

  def new
    @unit = current_user.units.build
  end

  def create
    @unit = current_user.units.build(unit_params)

    if @unit.save
      flash[:notice] = "Successfully added unit"
      redirect_to mypos_units_path
    else
      flash[:alert] = "Something went wrong"
      render "new"
    end
  end

  def edit
  end

  def update
    if @unit.update(unit_params)
      flash[:notice] = "Successfully updated unit"
      redirect_to mypos_unit_path(@unit)
    else
      flash[:alert] = "Something went wrong"
      render "edit"
    end
  end

  def destroy
    @unit.destroy
    flash[:notice] = "Successfully deleted unit"
    redirect_to mypos_units_path
  end

  private
    def find_unit
      @unit = Unit.find(params[:id])
    end

    def unit_params
      params.require(:unit).permit(:name)
    end
end

app/helpers/mypos/categories_helper.rb
module Mypos::CategoriesHelper
end

app/helpers/mypos/customers_helper.rb
module Mypos::CustomersHelper
end

app/helpers/mypos/dashboard_helper.rb
module Mypos::DashboardHelper
  def checking_profile
    current_user.company_name.blank?
    current_user.date_of_birth.blank?
    current_user.address.blank?
    current_user.city.blank?
    current_user.province.blank?
    current_user.zip.blank?
    current_user.country.blank?
  end
end

app/helpers/mypos/products_helper.rb
module Mypos::ProductsHelper
end

app/helpers/mypos/sales_helper.rb
module Mypos::SalesHelper
end

app/helpers/mypos/suppliers_helper.rb
module Mypos::SuppliersHelper
end

app/helpers/mypos/units_helper.rb
module Mypos::UnitsHelper
end

app/views/mypos/products/_allproducts.html.erb
<% @products.each do |p| %>
  <tr>
    <td><%= p.id %></td>
    <td><%= p.code_product %></td>
    <td><%= p.name %></td>
    <td><%= p.category.name %></td>
    <td><%= p.quantity %></td>
    <td>
      <%= link_to "Detail", mypos_product_path(p), class: "btn btn-xs btn-default" %>
      <%= link_to "Edit", edit_mypos_product_path(p), class: "btn btn-xs btn-primary" %>
      <a href="#deleteConfirm" data-toggle="modal" class="btn btn-xs btn-danger">Delete</a>
    </td>
  </tr>

  <div class="modal fade" id="deleteConfirm" tabindex="-1" role="dialog" aria-labelledby="deleteConfirm">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="deleteConfirm">Are you sure want to delete this?</h4>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
          <%= link_to "Yes", mypos_product_path(p), method: :delete, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/mypos/products/_form.html.erb
<%= simple_form_for ([:mypos, @product]), html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label>Product Code <small>(required)</small></label>
        <%= f.input :code_product, label: false, input_html: {class: "form-control"} %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label>Product Name <small>(required)</small></label>
        <%= f.input :name, label: false, input_html: {class: "form-control"} %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label>Category <small>(required)</small></label>
        <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a category"}, label: false, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label>Unit <small>(required)</small></label>
        <%= f.collection_select :unit_id, Unit.all, :id, :name, {prompt: "Choose a unit"}, label: false, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-12">
      <div class="form-group">
        <label>Size <small>(required)</small></label>
        <%= f.input :size, label: false, input_html: {class: "form-control"} %>
        <span class="help-block">10cm x 10cm, 5m x 5m, etc.</span>
      </div>
    </div>
    <div class="col-md-12">
      <div class="form-group">
        <label>Description <small>(required)</small></label>
        <%= f.text_area :description, rows: "5", class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label>Buy Cost <small>(required)</small></label>
        <div class="input-group">
          <span class="input-group-addon">$</span>
          <%= f.input :buy_cost, label: false, input_html: {class: "form-control"} %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label>Sell Cost <small>(required)</small></label>
        <div class="input-group">
          <span class="input-group-addon">$</span>
          <%= f.input :sell_cost, label: false, input_html: {class: "form-control"} %>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div class="form-group">
        <label>Quantity <small>(required)</small></label>
        <%= f.input :quantity, label: false, input_html: {class: "form-control"} %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.button :submit, class: "btn btn-primary" %>
        <%= link_to "Back", mypos_products_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>

app/views/mypos/products/edit.html.erb
<h3 class="title1"><%= current_user.company_name %> - Edit Product <small><%= show_time %></small></h3>
<div class="panel-body widget-shadow">
  <%= render "form" %>
</div>

app/views/mypos/products/index.html.erb
<h3 class="title1">
  <%= company_name %> <small><%= show_time %></small>
</h3>
<div class="panel-body widget-shadow">
  <%= link_to new_mypos_product_path, class: "btn btn-primary" do %>
    <i class="fa fa-plus"></i> Add New product
  <% end %>
  <div class="table-responsive">
    <table class="datatable table table-bordered table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>Code Product</th>
          <th>Name</th>
          <th>Category</th>
          <th>Quantity</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <%= render "allproducts" %>
      </tbody>
    </table>
  </div>
</div>

app/views/mypos/products/new.html.erb
<h3 class="title1"><%= current_user.company_name %> - Add New Product <small><%= show_time %></small></h3>
<div class="panel-body widget-shadow">
  <%= render "form" %>
</div>

app/views/mypos/products/show.html.erb
<h3 class="title1">
  <%= company_name %> <small><%= show_time %></small>
</h3>
<div class="panel-body widget-shadow">
  <table class="table">
    <tbody>
      <tr>
        <th>Product Code</th>
        <td>:</td>
        <td class="text-capitalize"><%= @product.code_product %></td>
      </tr>
      <tr>
        <th>Product Name</th>
        <td>:</td>
        <td class="text-capitalize"><%= @product.name %></td>
      </tr>
      <tr>
        <th>Category</th>
        <td>:</td>
        <td class="text-capitalize"><%= @product.category_id.name %></td>
      </tr>
      <tr>
        <th>Size</th>
        <td>:</td>
        <td><%= @product.size %></td>
      </tr>
      <tr>
        <th>Description</th>
        <td>:</td>
        <td class="text-capitalize">
          <%= @product.description %>
        </td>
      </tr>
      <tr>
        <th>Buy Cost</th>
        <td>:</td>
        <td class="text-capitalize"><%= number_to_currency(@product.buy_cost, precision: 2) %></td>
      </tr>
      <tr>
        <th>Sell Cost</th>
        <td>:</td>
        <td class="text-capitalize"><%= number_to_currency(@product.sell_cost, precision: 2) %></td>
      </tr>
      <tr>
        <th>Quantity</th>
        <td>:</td>
        <td class="text-capitalize"><%= @product.quantity %> <span class="text-capitalize"><%= @product.unit_id.name %></span></td>
      </tr>
    </tbody>
  </table>

  <%= link_to "Back", mypos_products_path, class: "btn btn-primary btn-sm" %>
  <%= link_to "Edit", edit_mypos_product_path(@product), class: "btn btn-primary btn-sm" %>
  <a href="#deleteConfirm" data-toggle="modal" class="btn btn-sm btn-danger">Delete</a>

  <div class="modal fade" id="deleteConfirm" tabindex="-1" role="dialog" aria-labelledby="deleteConfirm">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="deleteConfirm">Are you sure want to delete this?</h4>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
          <%= link_to "Yes", mypos_product_path(@product), method: :delete, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>

</div>