config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"

  namespace :mypos do
    get "dashboard", to: "dashboard#index"
    root to: "dashboard#index"

    resources :customers, :suppliers, :categories, :units, :products, :sales, :product_sellings
  end

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/mypos/dashboard_controller.rb
class Mypos::DashboardController < ApplicationController
  def index
    @customer = Customer.count
  end
end

app/helpers/mypos/dashboard_helper.rb
module Mypos::DashboardHelper
  def checking_profile
    current_user.company_name.blank?
    current_user.date_of_birth.blank?
    current_user.address.blank?
    current_user.city.blank?
    current_user.province.blank?
    current_user.zip.blank?
    current_user.country.blank?
  end
end

app/views/shared/dashboards/_footer.html.erb
<div class="footer">
   <p>&copy; 2017 FlatPos by <a href="https://facebook.com/adhamkurniawan29">Adham Kurniawan</a>. All Rights Reserved</p>
</div>

app/views/shared/dashboards/_nav.html.erb
<div class="sidebar" role="navigation">
  <div class="navbar-collapse">
    <nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
      <ul class="nav" id="side-menu">
        <li>
          <a href="<%= mypos_root_path %>"><i class="fa fa-home nav_icon"></i>Dashboard</a>
        </li>
        <li>
          <%= link_to mypos_customers_path do %>
            <i class="fa fa-circle-o nav_icon"></i> Customer
          <% end %>
        </li>
        <li>
          <%= link_to mypos_suppliers_path do %>
            <i class="fa fa-circle-o nav_icon"></i> Supplier
          <% end %>
        </li>
        <li>
          <a role="button" data-toggle="collapse" href="#collapseNavDash" aria-expanded="false" aria-controls="collapseNavDash"><i class="fa fa-circle-o nav_icon"></i>Items <span class="fa arrow"></span></a>
          <ul class="collapse nav nav-second-level" id="collapseNavDash">
            <li>
              <a href="<%= mypos_categories_path %>"><i class="fa fa-circle-o"></i> Category</a>
            </li>
            <li>
              <a href="<%= mypos_products_path %>"><i class="fa fa-circle-o"></i> Product</a>
            </li>
            <li>
              <a href="<%= mypos_units_path %>"><i class="fa fa-circle-o"></i> Unit</a>
            </li>
          </ul>
          <!-- /nav-second-level -->
        </li>
        <li>
          <%= link_to do %>
            <i class="fa fa-circle-o nav_icon"></i> Product Selling
          <% end %>
        </li>
      </ul>
      <!-- //sidebar-collapse -->
    </nav>
  </div>
</div>

<div class="sticky-header header-section ">
  <div class="header-left">
    <button id="showLeftPush"><i class="fa fa-bars"></i></button>
    <div class="logo">
      <a href="index.html">
        <h1>FlatPos</h1>
        <span>Dashboard</span>
      </a>
    </div>
    <!-- <div class="search-box">
      <form class="input">
        <input class="sb-search-input input__field--madoka" placeholder="Search..." type="search" id="input-31" />
        <label class="input__label" for="input-31">
          <svg class="graphic" width="100%" height="100%" viewBox="0 0 404 77" preserveAspectRatio="none">
            <path d="m0,0l404,0l0,77l-404,0l0,-77z"/>
          </svg>
        </label>
      </form>
    </div> -->
    <div class="clearfix"> </div>
  </div>
  <div class="header-right">
    <!--notifications of menu start -->
    <!-- <div class="profile_details_left">
      <ul class="nofitications-dropdown">
        <li class="dropdown head-dpdn">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
          <ul class="dropdown-menu">
            <li>
              <div class="notification_header">
                <h3>You have 3 new messages</h3>
              </div>
            </li>
            <li><a href="#">
               <div class="user_img"><img src="<%= image_path('dashboards/1.png') %>" alt=""></div>
               <div class="notification_desc">
              <p>Lorem ipsum dolor amet</p>
              <p><span>1 hour ago</span></p>
              </div>
               <div class="clearfix"></div>
            </a></li>
            <li class="odd"><a href="#">
              <div class="user_img"><img src="<%= image_path('dashboards/2.png') %>" alt=""></div>
               <div class="notification_desc">
              <p>Lorem ipsum dolor amet </p>
              <p><span>1 hour ago</span></p>
              </div>
              <div class="clearfix"></div>
            </a></li>
            <li><a href="#">
               <div class="user_img"><img src="<%= image_path('dashboards/3.png') %>" alt=""></div>
               <div class="notification_desc">
              <p>Lorem ipsum dolor amet </p>
              <p><span>1 hour ago</span></p>
              </div>
               <div class="clearfix"></div>
            </a></li>
            <li>
              <div class="notification_bottom">
                <a href="#">See all messages</a>
              </div>
            </li>
          </ul>
        </li>
        <li class="dropdown head-dpdn">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-bell"></i><span class="badge blue">3</span></a>
          <ul class="dropdown-menu">
            <li>
              <div class="notification_header">
                <h3>You have 3 new notification</h3>
              </div>
            </li>
            <li><a href="#">
              <div class="user_img"><img src="<%= image_path('dashboards/2.png') %>" alt=""></div>
               <div class="notification_desc">
              <p>Lorem ipsum dolor amet</p>
              <p><span>1 hour ago</span></p>
              </div>
              <div class="clearfix"></div>
             </a></li>
             <li class="odd"><a href="#">
              <div class="user_img"><img src="<%= image_path('dashboards/1.png') %>" alt=""></div>
               <div class="notification_desc">
              <p>Lorem ipsum dolor amet </p>
              <p><span>1 hour ago</span></p>
              </div>
               <div class="clearfix"></div>
             </a></li>
             <li><a href="#">
              <div class="user_img"><img src="<%= image_path('dashboards/3.png') %>" alt=""></div>
               <div class="notification_desc">
              <p>Lorem ipsum dolor amet </p>
              <p><span>1 hour ago</span></p>
              </div>
               <div class="clearfix"></div>
             </a></li>
             <li>
              <div class="notification_bottom">
                <a href="#">See all notifications</a>
              </div>
            </li>
          </ul>
        </li>
        <li class="dropdown head-dpdn">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-tasks"></i><span class="badge blue1">15</span></a>
          <ul class="dropdown-menu">
            <li>
              <div class="notification_header">
                <h3>You have 8 pending task</h3>
              </div>
            </li>
            <li><a href="#">
              <div class="task-info">
                <span class="task-desc">Database update</span><span class="percentage">40%</span>
                <div class="clearfix"></div>
              </div>
              <div class="progress progress-striped active">
                <div class="bar yellow" style="width:40%;"></div>
              </div>
            </a></li>
            <li><a href="#">
              <div class="task-info">
                <span class="task-desc">Dashboard done</span><span class="percentage">90%</span>
                 <div class="clearfix"></div>
              </div>
              <div class="progress progress-striped active">
                 <div class="bar green" style="width:90%;"></div>
              </div>
            </a></li>
            <li><a href="#">
              <div class="task-info">
                <span class="task-desc">Mobile App</span><span class="percentage">33%</span>
                <div class="clearfix"></div>
              </div>
               <div class="progress progress-striped active">
                 <div class="bar red" style="width: 33%;"></div>
              </div>
            </a></li>
            <li><a href="#">
              <div class="task-info">
                <span class="task-desc">Issues fixed</span><span class="percentage">80%</span>
                 <div class="clearfix"></div>
              </div>
              <div class="progress progress-striped active">
                 <div class="bar  blue" style="width: 80%;"></div>
              </div>
            </a></li>
            <li>
              <div class="notification_bottom">
                <a href="#">See all pending tasks</a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
      <div class="clearfix"> </div>
    </div> -->
    <!--notification menu end -->
    <div class="profile_details">
      <ul>
        <li class="dropdown profile_details_drop">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <div class="profile_img">
              <span class="prfil-img">
                <%= image_tag avatar_url(current_user), class: "img-circle" %>
              </span>
              <div class="user-name">
                <p><%= current_user.full_name %></p>
                <% if current_user.company_name.blank? %>
                  <span>No Company Name</span>
                <% else %>
                  <span><%= current_user.company_name %></span>
                <% end %>
              </div>
              <i class="fa fa-angle-down lnr"></i>
              <i class="fa fa-angle-up lnr"></i>
              <div class="clearfix"></div>
            </div>
          </a>
          <ul class="dropdown-menu drp-mnu">
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> Profile
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i> Logout
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="clearfix"> </div>
  </div>
  <div class="clearfix"> </div>
</div>